import './globals.css'
import type { Metadata } from 'next'
import { Sora } from 'next/font/google'
import { Nav, Header, TopLeftImg, AnimatePresenceComponent } from '@/components'

export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  icons: {
    icon: ['/metaIcons/home/favicon.ico?v=4'],
    apple: ['/metaIcons/home/apple-touch-icon.png?v=4'],
    shortcut: ['/metaIcons/home/apple-touch-icon.png'],
  },
  manifest: '/metaIcons/home/site.webmanifest',
}

//font
const sora = Sora({
  subsets: ['latin'],
  variable: '--font-sora',
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={` page bg-site bg-cover text-white bg-no-repeat ${sora.className}`}
      >
        <TopLeftImg />
        <Header />
        <AnimatePresenceComponent>{children}</AnimatePresenceComponent>
        <Nav />
      </body>
    </html>
  )
}
